### ISSUE TITLE
User Story: Event Organiser

### ISSUE THREAD

**Issue by WHLW27** [WHLW27/full-stack-framework-portfolio-project-4#1]
As an **Event Organiser** I can **contact the establishment** so that **i can organise and run events.**

###### Acceptance Criteria
- [ ] Clear contact information available on the site
- [x] Seamlessly contact the establishment. 

###### Tasks
- [x] Add Contact details in a clear location across all pages of the site.
