### ISSUE TITLE
User Story: Customer booking

### ISSUE THREAD

**Issue by WHLW27** [WHLW27/full-stack-framework-portfolio-project-4#2]
As a **customer** I can **book a table* so that **I can  eat at the grill**

###### Acceptance Criteria
- [ ] Book Table Facility
- [ ] Able to choose a table from a list.
- [ ] Able to choose a day of the week within open hours.
- [ ] Set number of people at the table.

###### Tasks
- [ ] Create a booking form
- [ ] Create a database to hold the booking information
