### ISSUE TITLE
User Story: Customer with Diet Issues

### ISSUE THREAD

**Issue by WHLW27** [WHLW27/full-stack-framework-portfolio-project-4#4]
As a **relative of a hypochondriac** I can **download a copy of the menu* so that **I can scrutinise the menu ingredients**

###### Acceptance Criteria
- [ ] Able to view a menu of the available food items on the site
- [ ] Able to download a basic copy of this menu for personal records
- [ ] Criteria 3

###### Tasks
- [ ] Add menu html structure
- [ ] Add download menu button.
- [ ] Add a dropdown with a menu, dietary information separated.
